apiVersion: v1
kind: Namespace
metadata:
  name: memsentinel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memsentinel
  namespace: memsentinel
  labels:
    app.kubernetes.io/name: memsentinel
    app.kubernetes.io/component: agent
